use_frameworks!

target 'WTYCommon_Example' do
  pod 'WTYCommon', :path => '../'

  target 'WTYCommon_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
